### ISSUE TITLE
mp3

### ISSUE THREAD

**Issue by RouR** [owoudenberg/soundtouch.net#1]
Does it support mp3-files?
Something like mp3InFile instead of WavInFile.
I need only DetectBpm() function

**Comment by Sojaner** [comment]
No @RouR MP3 is a commercial compression format meaning that you should decompress the file before you can see the actual raw wav format audio which is the first issue and secondly, because it is commercially licensed it's tricky to be included in free and open licensed software, hens no intention for supporting any Mp3InFile decompressor I guess. ;)

**Comment by RouR** [comment]
MP3 is not a commercial, sinse April 23, 2017 - https://www.iis.fraunhofer.de/en/ff/amm/prod/audiocodec/audiocodecs/mp3.html
